version: '3.7'
services:
    db:
        image: postgres:latest
        container_name: MyPostgreSQL
        restart: always
        hostname: postgresql
        volumes:
           - ./sql/create_schema.sql:/docker-entrypoint-initdb.d/create_schema.sql
           - ./sql/data.sql:/docker-entrypoint-initdb.d/data.sql
        environment:
            POSTGRES_DB: postgresdb
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin
        ports:
            - "5432:5432"